
# SEO settings
title: "Certifiable"
# title2: "" # default: ""
description: "Eyrie ⎈ PKI News and distribution"
keywords: "x509, certificates, pki, kvet.ch, crl, email"
# url: https://pki.kvet.ch # site url
url: http://localhost # site url

# baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "heiswayi"
#twitter_username: "HeiswayiNrird"
#comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Emory Lundberg"
  job      : "superuser"
  bio      : "Bon Vivant and Administrator of this rickety-ass PKI."
  thumb    : http://img01.incumbent.org/uploads/big/ab2a3a2085a6e88b29f6962a6d514e5f.jpg
  email    : emory@kvet.ch
  url      : https://incumbent.org
  github   : http://github.com/emory
  twitter  : http://twitter.com/incumbent
  facebook : https://www.facebook.com/incumbent
#  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@incumbent"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : news
    title: updates

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
